config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "categories#index"
  resources :categories

  get "/category/:id", to: "categories#show"

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy]
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"

  resources :attractions, only: [:show, :index] do
    resources :reviews, except: [:new, :show, :index], shallow: true
  end

end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
    has_many :reviews, dependent: :destroy
    belongs_to :category
end

app/models/avatar.rb
class Avatar < ApplicationRecord
    has_many :users, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :attractions, dependent: :destroy
end

app/models/helpful.rb
class Helpful < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :attraction
    belongs_to :user
end

app/models/unhelpful.rb
class Unhelpful < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, presence: true, uniqueness: true
    has_many :reviews, dependent: :destroy
    belongs_to :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController

    def index
        @attractions = Attraction.all
    end

    def show
        @attraction = Attraction.find(params[:id])
        @review = Review.new
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end

    def show
        @category = Category.find(params[:id])
        @attractions = @category.attractions.all
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
        @review = Review.new(review_params)
        @review.rating = params[:rating]
        @review.recommend = params[:recommend]
        @review.user = current_user
        @review.attraction_id = params[:attraction_id]
        @review.save
        redirect_to attraction_path(params[:attraction_id])
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy 
        redirect_to attraction_path(@review.attraction_id)
    end

    private
        def review_params
            params.require(:review).permit(:content, :rating, :recommend)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(name: params[:name])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in!"
        else
            flash.now.alert = "invalid login credentials - try again!"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        @avatars = Avatar.all
    end

    def create 
        @user = User.new(user_params)
        @user.avatar_id = params[:avatar_id]
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "You have successfully signed up!"
            redirect_to root_path
        else
            render :new
        end
        @user = User.update(user_params)
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = current_user
        @avatars = Avatar.all
    end

    def update
        @user = User.find(params[:id])
        @user.update_attributes(params.require(:user).permit(:location, :avatar_id))
        redirect_to user_path(@user)
    end
private

    def user_params
        params.require(:user).permit(:name, :password, :password_confirmation, :location, :avatar_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/index.html.erb
<h1 id="a-index-head">Attractions</h1>
<table class="highlight">
  <thead>
    <tr>
        <th>Attraction</th>
        <th>Category</th>
    </tr>
  </thead>
  <tbody>
    <% @attractions.each do |attraction| %>
      <tr>
        <td><%= link_to(attraction.name, attraction_path(attraction), :data => { turbolinks: false }) %></td>
        <td><%= link_to(attraction.category.genre, category_path(attraction.category)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/attractions/show.html.erb
<div id="a-page">
    <div class="a-head">
        <h3><%= @attraction.name %>
            <span style="position:absolute; right:22%">
                <i class="material-icons">thumb_up</i>
                <i class="material-icons">thumb_down</i>
            </span>
        </h3>
        <div id="a-image">
            <img src="<%= @attraction.ride_image %>">
        </div>
        <div id="a-description">
            <%= @attraction.description %>
        </div>
    </div>
    <div id="new-review">
        <h5>Well? Was it fun? Write your review...</h5>
        <%= form_for [@attraction, @review] do |f| %>
            <div class="field rf-content">
                <%= f.text_field :content %>
            </div>
            <div class"rf-options" style="display:flex">
                <div class="input-field col s12 m6 field stars">
                    <select name="rating">
                        <option value="" disabled selected>Rate this ride!</option>
                        <option value="1">★</option>
                        <option value="2">★★</option>
                        <option value="3">★★★</option>
                        <option value="4">★★★★</option>
                        <option value="5">★★★★★</option>
                    </select>
                </div>
                <div class="wyr">
                    <p>Would you recommend this attraction?</p>
                    <p class="field">
                        <label>
                            <input name="recommend" type="radio" value="true" />
                            <span>Yes</span>
                        </label>
                        <label>
                            <input name="recommend" type="radio" value="false" />
                            <span>No</span>
                        </label>
                    </p>
                </div>
            </div>
            <button class="btn waves-effect waves-light light-blue darken-4" type="submit" name="action">
            Submit
            </button>
        <% end %>
    </div>
    <div id="all-reviews">
        <h3>REVIEWS <span style="font-size:24px">(<%= @attraction.reviews.length %> reviews)</span></h3>
        <% @attraction.reviews.reverse.each do |review| %>
        <div class="review">
            <div>
                <%= link_to review.user.name, user_path(review.user) %> &nbsp;gave this attraction&nbsp;
                <%= "★" if review.rating == 1 %>
                <%= "★★" if review.rating == 2 %>
                <%= "★★★" if review.rating == 3 %>
                <%= "★★★★" if review.rating == 4 %>
                <%= "★★★★★" if review.rating == 5 %>
                &nbsp; on <%= review.user.created_at.strftime("%m/%d/%y") %>
                &nbsp; <%= link_to "Delete", review_path(review), method: "delete" if review.user == current_user %>                
            </div>
            <div>
                "<%= review.content %>"
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/categories/index.html.erb
<div id="landing-greeting">
    <h3>is it fun?</h3>
    <h5>Check out which rides are fun and share your experience</h5>
    <p>Which type of rider are you?</p>
    <div class="category-container">
        <% @categories.each do |category| %>
            <div class="category z-depth-3" style="background-image:url('<%= category.image %>')">
                <h3><%= link_to(category.genre, category_path(category)) %></h3>
            </div>
        <% end %>
    </div>
    <a href="/attractions">
    <button class="btn waves-effect light-blue darken-4" type="submit" name="action">all attractions >>
    </button>
    </a>
</div>

app/views/categories/show.html.erb
<h1 class="cat-name"><%= @category.genre %> Attractions</h1>
  <div class="row attraction">
    <% @attractions.each do |attraction| %>
    <div class="col s6 m4">
      <div class="card">
        <div class="card-action">
          <h6 class="truncate cat-card-title"><a href="#" class="truncate"><%= link_to(attraction.name, attraction_path(attraction), :data => { turbolinks: false }) %></a>
          </h6>
        </div>
        <div class="card-image">
          <img src="<%= attraction.ride_image %>">
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Is It Fun?</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Mouse+Memoirs" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <nav>
      <div class="nav-wrapper light-blue darken-4">
        <ul id="nav" class="left">
          <li><a href="/" class="brand-logo">is it fun?</a></li>
          <li><%= link_to image_tag("https://image.flaticon.com/icons/svg/1/1010.svg"), root_path %></li>
        </ul>
        <ul id="nav" class="right">
          <% if current_user %>
            <li>Welcome, </li>
            <li><%= link_to current_user.name, user_path(current_user) %></li>
            <li><%= link_to "Edit Profile", edit_user_path(current_user), :data => { turbolinks: false } %></li>
            <li><%= link_to "Log Out", session_path("dummy"), method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", login_path %></li>
            <li><%= link_to "Sign Up", new_user_path, :data => { turbolinks: false } %></li>
          <% end %>
        </ul>
      </div>  
    </nav>
    <%= yield %> 
  </body>
</html>

app/views/users/edit.html.erb
<div class="form-page">
    <h1>Edit Profile</h1>
    <div class="user-form">
        <%= form_for @user do |f| %>
            <div class="field">
                <%= f.label :location %>
                <%= f.text_field :location %>
            </div>
            <div class="input-field col s12 m6">
                <%= select(:user, :avatar_id, class: "icons") do %>
                    <option value="" disabled selected>Who's your favorite Disney character?</option>
                    <% @avatars.each do |avatar| %>
                        <option value="<%= avatar.id %>" <%= @user.avatar == avatar ? ' selected ' : '' %> data-icon="<%= avatar.avatar_image %>"><%= avatar.avatar_name %></option>
                    <% end %>
                <% end %>
            </div>
            <div class="actions">
                <button class="btn waves-effect light-blue darken-4" type="submit" name="action">
                    <%= f.submit %>
                </button>
            </div>
        <% end %>
    </div>
</div>

app/views/users/new.html.erb
<div class="form-page">
<h1>Sign Up!</h1>
<div class="user-form">
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
                <% for message in @user.errors.full_messages %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <%= f.label :username %>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
        <%= f.label :location %>
        <%= f.text_field :location %>
    </div>
    <div class="input-field col s12 m6">
        <select class="icons" name="avatar_id">
            <option value="" disabled selected>Who's your favorite Disney character?</option>
            <% @avatars.each do |avatar| %>
                <option value="<%= avatar.id %>" data-icon="<%= avatar.avatar_image %>"><%= avatar.avatar_name %></option>
            <% end %>
        </select>
    </div>
    <div class="actions">
        <button class="btn waves-effect light-blue darken-4" type="submit" name="action">
            <%= f.submit %>
        </button>
    </div>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="profile-container">
<div class="profile-info">
    <div class="profile-name">
        <div><%= @user.name %> from <%= @user.location %></div>
    </div>
    <div class="profile-image">
        <img src="<%= @user.avatar.avatar_image %>">
    </div>
</div>
    <div id="all-reviews" class="profile-reviews">
        <h3>REVIEWS <span style="font-size:24px">(<%= @user.reviews.length %> reviews)</span></h3>
        <% @user.reviews.reverse.each do |review| %>
        <div class="review">
            <div>
                <%= review.user.name %> rated <%= link_to review.attraction.name, attraction_path(review.attraction), :data => { turbolinks: false } %>&nbsp;
                <%= "★" if review.rating == 1 %>
                <%= "★★" if review.rating == 2 %>
                <%= "★★★" if review.rating == 3 %>
                <%= "★★★★" if review.rating == 4 %>
                <%= "★★★★★" if review.rating == 5 %>
                on <%= review.user.created_at.strftime("%m/%d/%y") %>
                &nbsp; <%= link_to "Delete", review_path(review), method: "delete" if review.user == current_user %>                
            </div>
            <div>
                "<%= review.content %>"
            </div>
        </div>
        <% end %>
    </div>
</div>